replicaCount: 1
image:
  tag: "1.0"
service:
  type: NodePort
ingress:
  enabled: false
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
config:
  spring_profiles_active: "dev"
secrets:
  postgres_password: "dev-pass-123"
