apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-service-chart.fullname" . }}
  labels:
    app: {{ include "order-service-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.secrets.postgres_password | b64enc | quote }}
