apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service-chart.fullname" . }}
  labels:
    app: {{ include "order-service-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "order-service-chart.name" . }}
